DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS authors;
DROP SEQUENCE IF EXISTS global_seq;

CREATE SEQUENCE GLOBAL_SEQ AS BIGINT START WITH 100000;

CREATE TABLE authors
(
  id               BIGINT GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name             VARCHAR(255)           NOT NULL,
  surname          VARCHAR(255)           NOT NULL,
  patronymic       VARCHAR(255)           NOT NULL,
  birthday         DATE                   NOT NULL
);

CREATE TABLE books
(
  id      BIGINT GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name    VARCHAR(255)     NOT NULL,
  isbn    VARCHAR(255)     NOT NULL,
  subject VARCHAR(255)     NOT NULL,
  auth_id         BIGINT,
  FOREIGN KEY (auth_id) REFERENCES authors(id)
);

DELETE FROM authors;
DELETE FROM books;

INSERT INTO authors (name, patronymic, surname, birthday) VALUES
  ('Александр', 'Сергеевич','Пушкин', '1799-06-06'),
  ('Николай', 'Васильевич','Гоголь', '1809-04-01'),
  ('Михаил', 'Юрьевич','Лермонтов', '1814-10-05'),
  ('Test', 'Test','Test', '1929-01-11'),
  ('test2', 'test2','test2', '1929-01-11');

INSERT INTO books (name, isbn, subject, auth_id) VALUES
  ('Руслан и Людмила', '321-TT', 'Поэма', 100000),
  ('Дубровский', '311-TG', 'Повесть', 100000),
  ('Мертвые души', '417-GL', 'Поэма', 100001),
  ('Ревизор', '301-GG', 'Комедия', 100001),
  ('Мцыри', '3012-GG', 'Поэма', 100002);